---
- name: Install Java 1.8
  yum: name=java-1.8.0-openjdk state=present

- name: add group "tomcat"
  group: name={{tomcat_group}}

- name: add user "tomcat"
  user: name={{tomcat_user}} group={{tomcat_group}} home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: url=https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz dest=/opt/apache-tomcat-8.5.81.tar.gz

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-8.5.81.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.5.81

- name: Symlink install directory
  file: src=/opt/apache-tomcat-8.5.81 path=/opt/tomcat state=link

- name: Configure Tomcat server
  template: src=context.xml dest=/opt/tomcat/webapps/manager/META-INF/

- name: Configure Tomcat server
  template: src=host_context.xml dest=/opt/tomcat/webapps/host-manager/META-INF/context.xml

- name: Configure Tomcat server
  template: src=tomcat-users.xml dest=/opt/tomcat/conf/

- name: Change ownership of Tomcat installation
  file: path=/opt/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: copy war file
  copy: src=./target/LoginWebApp-1.war dest=/opt/apache-tomcat-8.5.81/webapps/


  notify: restart tomcat

- name: Install Tomcat Service
  copy: src=tomcat.service dest=/etc/systemd/system/tomcat.service

- name: reload systemd
  command: systemctl daemon-reload

- name: Start Tomcat
  systemd: name=tomcat state=started enabled=yes

